[package]
name = "token_bound_accounts"
version = "0.3.0"
edition = "2023_10"
authors = ["Starknet Africa Community <starknetafrica@gmail.com>"]
description = "A port of ERC6551 to Starknet"
repository = "https://github.com/Starknet-Africa-Edu/TBA/blob/main/Scarb.toml"
license-file = "LICENSE"
keywords = ["ERC6551", "tokenbound", "cairo", "contracts", "starknet", "standards"]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[[target.starknet-contract]]
sierra = true
casm = true

[lib]

[dependencies]
starknet = "2.6.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.20.1" }

[tool.snforge]
# exit_first = true