[package]
name = "token_bound_accounts"
version = "0.3.0"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = "2.6.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.20.1" }

[tool.snforge]
# exit_first = true