[package]
name = "token_bound_accounts"
version = "0.3.1"
edition = "2024_07"
authors = ["Horus Labs <horuslabsio@gmail.com>"]
description = "A port of ERC6551 to Starknet"
repository = "https://github.com/horuslabsio/TBA/blob/main/Scarb.toml"
license-file = "LICENSE"
keywords = ["ERC6551", "tokenbound", "cairo", "contracts", "starknet", "standards"]
readme = "README.md"
cairo_version = "2.8.2"
homepage = "https://www.tbaexplorer.com/"
documentation = "https://github.com/horuslabsio/TBA-SDK"

[[target.starknet-contract]]
sierra = true
casm = true

[lib]

[dependencies]
starknet = "2.10.1"
openzeppelin_introspection = "1.0.0"
openzeppelin_token = "1.0.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.44.0" }

[tool.snforge]
# exit_first = true

[scripts]
test = "snforge test"
